export const translateOptions = Object.freeze({
	"Dansk Frimur" : "dk-frimur",
	"Engelsk Frimur" : "en-frimur",
	"Gamle Runer" : "runer-gammel",
	"Middelalder-runer" : "runer-middelalder",
	"Klassisk Semafor" : "semafor-1",
	"Blindskrift" : "blindskrift"
})

export const translateTable = Object.freeze({
	"blindskrift" : {
		"path" : "blindskrift",
		"translations" : {
			"a" : "a.png",
			"b" : "b.png",
			"c" : "c.png",
			"d" : "d.png",
			"e" : "e.png",
			"f" : "f.png",
			"g" : "g.png",
			"h" : "h.png",
			"i" : "i.png",
			"j" : "j.png",
			"k" : "k.png",
			"l" : "l.png",
			"m" : "m.png",
			"n" : "n.png",
			"o" : "o.png",
			"p" : "p.png",
			"q" : "q.png",
			"r" : "r.png",
			"s" : "s.png",
			"t" : "t.png",
			"u" : "u.png",
			"v" : "v.png",
			"w" : "w.png",
			"x" : "x.png",
			"y" : "y.png",
			"z" : "z.png",
			"æ" : "ae.png",
			"ø" : "oe.png",
			"å" : "aa.png",
			"1" : "a.png",
			"2" : "b.png",
			"3" : "c.png",
			"4" : "d.png",
			"5" : "e.png",
			"6" : "f.png",
			"7" : "g.png",
			"8" : "h.png",
			"9" : "i.png",
		}
	},
	"runer-middelalder" : {
		"path" : "runer/middelalder",
		"translations" : {
			"a" : "a.png",
			"b" : "b.png",
			"c" : "c.png",
			"d" : "c.png",
			"e" : "e.png",
			"f" : "f.png",
			"g" : "g.png",
			"h" : "h.png",
			"i" : "i.png",
			"k" : "k.png",
			"l" : "l.png",
			"m" : "m.png",
			"n" : "n.png",
			"o" : "o.png",
			"p" : "p.png",
			"q" : "k.png",
			"r" : "r.png",
			"s" : "s.png",
			"t" : "t.png",
			"u" : "u.png",
			"v" : "v.png",
			"y" : "y.png",
			"z" : "z.png",
			"æ" : "ae.png",
			"ø" : "oe.png",
		}
	},
	"runer-gammel" : {
		"path" : "runer/gamle",
		"translations" : {
			"a" : "a.png",
			"b" : "b.png",
			"d" : "d.png",
			"e" : "e.png",
			"f" : "f.png",
			"g" : "g.png",
			"h" : "h.png",
			"i" : "i.png",
			"j" : "j.png",
			"k" : "k.png",
			"l" : "l.png",
			"m" : "m.png",
			"n" : "n.png",
			"o" : "o.png",
			"p" : "p.png",
			"r" : "r.png",
			"s" : "s.png",
			"t" : "t.png",
			"u" : "u.png",
			"w" : "w.png",
		}
	},
	"semafor-1" : {
		"path" : "semafor",
		"translations" : {
			"a" : "a.png",
			"b" : "b.png",
			"c" : "c.png",
			"d" : "d.png",
			"e" : "e.png",
			"f" : "f.png",
			"g" : "g.png",
			"h" : "h.png",
			"i" : "i.png",
			"j" : "j.png",
			"k" : "k.png",
			"l" : "l.png",
			"m" : "m.png",
			"n" : "n.png",
			"o" : "o.png",
			"p" : "p.png",
			"q" : "q.png",
			"r" : "r.png",
			"s" : "s.png",
			"t" : "t.png",
			"u" : "u.png",
			"v" : "v.png",
			"w" : "w.png",
			"x" : "x.png",
			"y" : "y.png",
			"z" : "z.png",
			"1" : "a.png",
			"2" : "b.png",
			"3" : "c.png",
			"4" : "d.png",
			"5" : "e.png",
			"6" : "f.png",
			"7" : "g.png",
			"8" : "h.png",
			"9" : "i.png",
		}
	},
	"dk-frimur" : {
		"path" : "frimur",
		"translations" : {
			"a" : "0-1.png",
			"b" : "0-2.png",
			"c" : "0-3.png",
			"d" : "0-4.png",
			"e" : "0-5.png",
			"f" : "0-6.png",
			"g" : "0-7.png",
			"h" : "0-8.png",
			"i" : "0-9.png",
			"j" : "1-1.png",
			"k" : "1-2.png",
			"l" : "1-3.png",
			"m" : "1-4.png",
			"n" : "1-5.png",
			"o" : "1-6.png",
			"p" : "1-7.png",
			"r" : "1-8.png",
			"s" : "1-9.png",
			"t" : "2-1.png",
			"u" : "2-2.png",
			"v" : "2-3.png",
			"x" : "2-4.png",
			"y" : "2-5.png",
			"z" : "2-6.png",
			"æ" : "2-7.png",
			"ø" : "2-8.png",
			"å" : "2-9.png",
			"1" : "3-1.png",
			"2" : "3-2.png",
			"3" : "3-3.png",
			"4" : "3-4.png",
			"5" : "3-5.png",
			"6" : "3-6.png",
			"7" : "3-7.png",
			"8" : "3-8.png",
			"9" : "3-9.png",
		}
	},
	"en-frimur" : {
		"path" : "frimur",
		"translations" : {
			"a" : "0-1.png",
			"b" : "0-2.png",
			"c" : "0-3.png",
			"d" : "0-4.png",
			"e" : "0-5.png",
			"f" : "0-6.png",
			"g" : "0-7.png",
			"h" : "0-8.png",
			"i" : "0-9.png",
			"j" : "1-1.png",
			"k" : "1-2.png",
			"l" : "1-3.png",
			"m" : "1-4.png",
			"n" : "1-5.png",
			"o" : "1-6.png",
			"p" : "1-7.png",
			"q" : "1-8.png",
			"r" : "1-9.png",
			"s" : "4-1.png",
			"t" : "4-2.png",
			"u" : "4-3.png",
			"v" : "4-4.png",
			"w" : "5-1.png",
			"x" : "5-2.png",
			"y" : "5-3.png",
			"z" : "5-4.png",
		}
	}

})
